### ISSUE TITLE
Topic contains non-JSON payload

### ISSUE THREAD

**Issue by walduino** [jpmens/mqtt2graphite#12]
Thanks for the great program !
Got a little problem though, while trying to parse the mqtt jason data from my sonoff tasmota IoT things, I'm getting  **Topic /tele/sonoff/SENSOR contains non-JSON payload**. I'm no JSON wizzard but this seems to be valid JSON no ? Any ideas ?

mqtt2graphite log
`2018-01-16 18:46:48,813 Topic /tele/sonoff/SENSOR contains non-JSON payload [{"Time":"2018-01-16T18:46:48","ENERGY":{"Total":0.874,"Yesterday":0.000,"Today":0.874,"Period":0,"Power":0,"Factor":0.00,"Voltage":228,"Current":0.000}}]`

MQTT message
`{"Time":"2018-01-16T18:40:48","ENERGY":{"Total":0.861,"Yesterday":0.000,"Today":0.861,"Period":6,"Power":720,"Factor":1.00,"Voltage":225,"Current":3.128}}`

**Comment by walduino** [comment]
The problem is the "ENERGY" subdocument appartently, the nicest way to solve this would probably be to add the json hierarchy to the carbonkey. This would fix any duplicate key/values in diff subdocs.
But that seems to be out of my python leage....

**Comment by jpmens** [comment]
What you've posted is indeed valid JSON. I'm *assuming* that the payload contains newlines or whatnot which we're not getting ...

Please point a `mosquitto_sub` at your broker and grab the payload into a file. See if you see anything untoward such as multiple lines please.

**Comment by walduino** [comment]
Hey thanks for the quick reaction, the problem was with the subdocument 'energy', it seems
Ive flattened the JSON and it now works great.
```
                   from pandas.io.json import json_normalize
                   st  = json_normalize(json.loads(msg.payload)) 

```

https://github.com/walduino/mqtt2graphite/commit/4afe3fb0d6fe0dfee96b816b0fc47dc143b4fe96#diff-415ee0750ca5df4f24c6392b567dea86

This is probably not PR worthy as i'm loading the whole panda thing for a simple function

From one of the messaes like the above, I now get data to graphite
2018-01-17 02:09:24,169 CARBONKEY is [sonoff.boiler]
2018-01-17 02:09:24,181 sonoff.boiler.ENERGY.Current 6.886000 1516151364
sonoff.boiler.ENERGY.Factor 1.000000 1516151364
sonoff.boiler.ENERGY.Period 14.000000 1516151364
sonoff.boiler.ENERGY.Power 1605.000000 1516151364
sonoff.boiler.ENERGY.Today 0.213000 1516151364
sonoff.boiler.ENERGY.Total 0.223000 1516151364
sonoff.boiler.ENERGY.Voltage 226.000000 1516151364
sonoff.boiler.ENERGY.Yesterday 0.009000 1516151364

**Comment by jpmens** [comment]
Glad you fixed it. We should  keep the panda normalizer in mind.
